driver=nl80211
country_code=US

ctrl_interface=/run/hostapd
ctrl_interface_group=0

# White list
macaddr_acl=1
accept_mac_file=/etc/hostapd.accept

logger_stdout=-1
logger_stdout_level=0

# ===== 5GHz band =====
hw_mode=a
channel=36

ieee80211n=1
ieee80211ac=1
ieee80211ax=1

ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][LDPC][TX-STBC][RX-STBC1]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

he_oper_chwidth=1
he_oper_centr_freq_seg0_idx=42

# ===== security =====
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
ieee80211w=2

# ===== performance =====
ieee80211d=1
ieee80211h=1
