HOSTNAME=arch
SWAP_SIZE=16GB
ZRAM_SIZE=RAM/2

##
## Efibootmgr setup following `/etc/fstab`
##
EFINAME=Arch

## CPU Encode
# UCODE=amd
UCODE=intel

##
## Login Manager
##
LOGIN_MANAGER=lemurs # sddm gdm lightdm

###
### GPU
###
GPU=intel # nvidia amd

##
## Services
##
SERVICES=(NetworkManager bluetooth)

##
## /etc/locale.conf
##
LANG=en_US.UTF-8
KEYMAP=us

##
## timedatectl
##
TIMEZONE=Asia/Singapore
