HOSTNAME=arch
SWAP_SIZE=32GB
ZRAM_SIZE=RAM/2

##
## Efibootmgr setup following `/etc/fstab`
##
EFINAME=Arch

## CPU Encode
# UCODE=amd
UCODE=amd

##
## Login Manager
##
LOGIN_MANAGER=lemurs # sddm gdm lightdm

###
### GPU
###
GPU=nvidia # nvidia amd

##
## Services
##
SERVICES=(NetworkManager bluetooth)

##
## /etc/locale.conf
##
LANG=en_US.UTF-8
KEYMAP=us

##
## timedatectl
##
TIMEZONE=Asia/Singapore
